# Generated by Django 6.1 on 2026-08-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200)),
                ('rok_vydani', models.PositiveIntegerField()),
                ('hodnoceni', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Hodnocení 1-5 hvězdiček', null=True)),
                ('poznamka', models.TextField(blank=True)),
                ('datum_pridani', models.DateTimeField(auto_now_add=True)),
                ('interpret', models.CharField(max_length=200)),
                ('zanr', models.CharField(blank=True, max_length=100)),
                ('pocet_skladeb', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('format', models.CharField(choices=[('cd', 'CD'), ('vinyl', 'Vinyl'), ('digital', 'Digitální')], default='cd', max_length=10)),
            ],
            options={
                'ordering': ['-datum_pridani'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200)),
                ('rok_vydani', models.PositiveIntegerField()),
                ('hodnoceni', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Hodnocení 1-5 hvězdiček', null=True)),
                ('poznamka', models.TextField(blank=True)),
                ('datum_pridani', models.DateTimeField(auto_now_add=True)),
                ('reziser', models.CharField(max_length=200)),
                ('zanr', models.CharField(blank=True, max_length=100)),
                ('delka_minuty', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('format', models.CharField(choices=[('dvd', 'DVD'), ('bluray', 'Blu-ray'), ('streaming', 'Streaming')], default='dvd', max_length=10)),
            ],
            options={
                'ordering': ['-datum_pridani'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kniha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200)),
                ('rok_vydani', models.PositiveIntegerField()),
                ('hodnoceni', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Hodnocení 1-5 hvězdiček', null=True)),
                ('poznamka', models.TextField(blank=True)),
                ('datum_pridani', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(max_length=200)),
                ('zanr', models.CharField(blank=True, max_length=100)),
                ('pocet_stran', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('format', models.CharField(choices=[('papir', 'Papírová'), ('ekniha', 'E-kniha'), ('audiokniha', 'Audiokniha')], default='papir', max_length=10)),
            ],
            options={
                'ordering': ['-datum_pridani'],
                'abstract': False,
            },
        ),
    ]
